### ISSUE TITLE
DM Stealth Members

### ISSUE THREAD

**Issue by TheSeaCreature** [Stealth-Robotics/Team#7]

**Comment by TheSeaCreature** [comment]
Also remind me to pester Ashlyn and Danika for the roster

**Comment by TheSeaCreature** [comment]
@silverlightning926  Are you going to dm miyoshi?

**Comment by silverlightning926** [comment]
@TheSeaCreature I don't think so, I'll just DM students right now

**Comment by silverlightning926** [comment]
I have reached out to all the people I could on Slack.
